//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dishes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dishes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishes.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really remove dish &quot;{0}&quot;?.
        /// </summary>
        public static string ConfirmRemoveDish {
            get {
                return ResourceManager.GetString("ConfirmRemoveDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really remove source &quot;{0}&quot;?.
        /// </summary>
        public static string ConfirmRemoveSource {
            get {
                return ResourceManager.GetString("ConfirmRemoveSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really remove tag &quot;{0}&quot;?.
        /// </summary>
        public static string ConfirmRemoveTag {
            get {
                return ResourceManager.GetString("ConfirmRemoveTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string DishCommentLabel {
            get {
                return ResourceManager.GetString("DishCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishes.
        /// </summary>
        public static string DishesTabTitle {
            get {
                return ResourceManager.GetString("DishesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string DishPathLabel {
            get {
                return ResourceManager.GetString("DishPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string DishSourceLabel {
            get {
                return ResourceManager.GetString("DishSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FindLabel {
            get {
                return ResourceManager.GetString("FindLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string IdLabel {
            get {
                return ResourceManager.GetString("IdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoOfUsages.
        /// </summary>
        public static string NoOfUsages {
            get {
                return ResourceManager.GetString("NoOfUsages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove dish.
        /// </summary>
        public static string RemoveDish {
            get {
                return ResourceManager.GetString("RemoveDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove source.
        /// </summary>
        public static string RemoveSource {
            get {
                return ResourceManager.GetString("RemoveSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tag.
        /// </summary>
        public static string RemoveTag {
            get {
                return ResourceManager.GetString("RemoveTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string SourcesTabTitle {
            get {
                return ResourceManager.GetString("SourcesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsTabTitle {
            get {
                return ResourceManager.GetString("TagsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
